### ISSUE TITLE
Compilers minimum version

### ISSUE THREAD

**Issue by victor1234** [lemire/streamvbyte#55]
What are the requirements for the gcc, clang, MSVC compilers version other than C99 support?

**Comment by lemire** [comment]
We currently support GCC 9 and Visual Studio 17 2022. Please see our continuous integration tests.

Do you want to contribute more GitHub actions so that we can test a wider range of compilers and systems?

**Comment by victor1234** [comment]
I'm working on a `streamvbyte` package for [сonan](https://conan.io/) and I need to set minimum compilers version in package config. C99 supports by many compilers, but perhaps there are some other limitations

**Comment by lemire** [comment]
I have added an extensive collection of CI tests and I have updated the README:

# Requirements

* A C99 compatible compiler (GCC 9 and up, LLVM 10 and up, Visual Studio 2019 and up).
* We support macOS, Linux and Windows. It should be easy to extend support to FreeBSD and other POSIX systems.

For high performance, you should have either a 64-bit ARM processor or a 64-bit x64 system with SSE 4.1 support. SSE 4.1 was added to Intel processors in 2007 so it is almost certain that your Intel or AMD processor supports it.


----

It is possible that older compilers could be supported but I cannot easily support them because I do not have convenient CI support.

**Comment by lemire** [comment]
Closing.
